feat(locales): add Spanish translations
qbcore-framework/qb-management pull request #130
Opened 2024-11-14 12:30 UTC by Cocodrulo

**Describe Pull request**
This PR brings the Spanish locale to the management script.

If your PR is to fix an issue mention that issue here: No

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (But they are just locale it shouldn't be any problem at all)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2024-11-14 14:13 UTC, IDKFORCE requested changes
You should make the spanish more traditional as center as posible like for example
This

```
 ['exit'] = 'Volver',
 ```
 Should Be
 
```
 ['exit'] = 'Cerrar',
 ```
 
 also gestionar empleados could be like manejar empleados
 is more central spanish gotta think outside of your dialogue also lots of people use ganga not really banda thats more mexican dialogue
 
 like i would do it like this
 ```
local Translations = {
    headers = {
        ['bsm'] = 'Menú de Jefe - ',
    },
    body = {
        ['manage'] = 'Manejar empleados',
        ['managed'] = 'Revisa tu lista de empleados',
        ['hire'] = 'Contratar empleados',
        ['hired'] = 'Contratar civiles cercanos',
        ['storage'] = 'Acceso a almacenamiento',
        ['storaged'] = 'Abrir almacenamiento',
        ['outfits'] = 'Vestimenta',
        ['outfitsd'] = 'Ver vestimenta guardada',
        ['money'] = 'Manejo de dinero',
        ['moneyd'] = 'Revisar el saldo de tu empresa',
        ['mempl'] = 'Manejar empleados - ',
        ['mngpl'] = 'Manejar ',
        ['grade'] = 'Rango: ',
        ['fireemp'] = 'Despedir empleado',
        ['hireemp'] = 'Contratar empleados - ',
        ['cid'] = 'ID de ciudadano: ',
        ['balance'] = 'Saldo: $',
        ['deposit'] = 'Depositar',
        ['depositd'] = 'Depositar dinero en la cuenta',
        ['withdraw'] = 'Retirar',
        ['withdrawd'] = 'Retirar dinero de la cuenta',
        ['depositm'] = 'Depositar dinero <br> Saldo disponible: $',
        ['withdrawm'] = 'Retirar dinero <br> Saldo disponible: $',
        ['submit'] = 'Confirmar',
        ['amount'] = 'Cantidad',
        ['return'] = 'Volver',
        ['exit'] = 'Cerrar',
    },
    drawtext = {
        ['label'] = '[E] Abrir manejo de trabajo',
    },
    target = {
        ['label'] = 'Menú de Jefe',
    },
    headersgang = {
        ['bsm'] = 'Manejo de Ganga - ',
    },
    bodygang = {
        ['manage'] = 'Manejar miembros de la ganga',
        ['managed'] = 'Reclutar o despedir miembros de la ganga',
        ['hire'] = 'Reclutar miembros',
        ['hired'] = 'Contratar miembros de la ganga',
        ['storage'] = 'Acceso a almacenamiento',
        ['storaged'] = 'Abrir Inventario de la ganga',
        ['outfits'] = 'Vestimenta',
        ['outfitsd'] = 'Cambiar de vestimenta',
        ['money'] = 'Manejo de dinero',
        ['moneyd'] = 'Revisar el saldo de tu ganga',
        ['mempl'] = 'Manejar miembros de la ganga - ',
        ['mngpl'] = 'Manejar ',
        ['grade'] = 'Rango: ',
        ['fireemp'] = 'Despedir',
        ['hireemp'] = 'Contratar miembros de la ganga - ',
        ['cid'] = 'ID de ciudadano: ',
        ['balance'] = 'Saldo: $',
        ['deposit'] = 'Depositar',
        ['depositd'] = 'Depositar dinero en la cuenta',
        ['withdraw'] = 'Retirar',
        ['withdrawd'] = 'Retirar dinero de la cuenta',
        ['depositm'] = 'Depositar dinero <br> Saldo disponible: $',
        ['withdrawm'] = 'Retirar dinero <br> Saldo disponible: $',
        ['submit'] = 'Confirmar',
        ['amount'] = 'Cantidad',
        ['return'] = 'Volver',
        ['exit'] = 'Cerrar',
    },
    drawtextgang = {
        ['label'] = '[E] Abrir manejo de la ganga',
    },
    targetgang = {
        ['label'] = 'Menú de la Ganga',
    }
}

if GetConvar('qb_locale', 'en') == 'es' then
    Lang = Lang or Locale:new({
        phrases = Translations,
        warnOnMissing = true
    })
end
```

2024-11-14 14:20 UTC, Cocodrulo commented
About the Volver and Cerrar I agree with u, but the others ones, not really. I'm from Spain as most of other members of my RP server. And I have not heard "Ganga" referring to a Gang in my entire life. I'm heard "gangs" as a word to say bargain. So I'll change the Volver but no the other one.

2024-11-14 14:31 UTC, IDKFORCE commented
i understand you have a spain community but you also gotta understand the spanish has to be as central as posible like 
```
 ['manage'] = 'Gestionar empleados',
```
 to
```
['manage'] = 'Manejar empleados',
```

or
```
 ['amount'] = 'Monto',
```
to
```
 ['amount'] = 'Cantidad',
 ```
 
 ```
 ['manage'] = 'Manejar miembros de la banda',
 ```
 to
 ```
  ['manage'] = 'Manejar miembros de la pandilla',
 ```

2024-11-14 14:42 UTC, Cocodrulo commented
I think that's not the actitude. If I think you are not correct, I'll tell you, I'm not telling you that you are completely wrong, only that that is not the Spanish I know from my experience of being from a part of Spain and from my other friends that are from other parts of Spain.

This language is rich and with lots of different words to say same things. But ones are more used than others, and those are the ones that I try to use.

No need to say those things btw.

2024-11-14 18:48 UTC, Qwerty1Verified commented
I think it's best to have the most diverse language, that being the one that has more people behind it.

2024-11-14 18:52 UTC, Cocodrulo commented
I put the one I think is more used, at least the one I here more in TV, oficial speeches from Spain institutions, etc

2024-11-26 18:47 UTC, Cocodrulo commented
Is this going to me merged?

2025-01-26 20:14 UTC, Cocodrulo commented
hello?

2025-02-08 01:25 UTC, Qwerty1Verified approved these changes

2025-02-13 15:01 UTC, merged