feat(client): Dynamic Menu items
qbcore-framework/qb-management pull request #63
Opened 2022-07-15 09:34 UTC by TheiLLeniumStudios

**Describe Pull request**
Allows other resources to inject Boss Menu items. Very useful when you need to extend the functionality of Boss Menu through an external resource without modifying qb-management

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

2022-07-16 19:54 UTC, jnccloud approved these changes
I have ran this with up to 100 users in the server and have had not a single complaint. I think it's ready to be merged. Perhaps an "Exit" or "Return" menu should be automatically generated, but that's not a show stopper. This is a great addition.

2022-07-16 20:49 UTC, TheiLLeniumStudios commented
@jnccloud That exit / return can only come from the resource that adds the menu, so as far as this change is concerned, it is complete

2022-07-16 21:35 UTC, iktray approved these changes

2022-07-18 19:05 UTC, BerkieBb requested changes

2022-07-18 19:19 UTC, BerkieBb approved these changes

2022-07-22 19:11 UTC, merged